spring:
  application:
    name: payment-service-9001

  datasource:
    url: jdbc://mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka,http://peer2:8002/eureka

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mapper/*.xml