spring:
  application:
    name: eureka-server-8002

server:
  port: 8002

eureka:
  instance:
    hostname: peer2

  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://peer1:8001/eureka