spring:
  application:
    name: eureka-server

server:
  port: 20001

eureka:
  instance:
    hostname: eureka.20001

  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka.20000:20000/eureka/